### ISSUE TITLE
Failed to upload iOS release

### ISSUE THREAD

**Issue by nguyenduythuc** [nickwph/firebase-app-distribution-action#1]
* Hi, i'm using github action to upload iOS and Android to Firebase app distribution and got this error

- Source code:
`- name: Upload build file`
`      uses: nickwph/firebase-app-distribution-action@v1`
`      with:`
`        app: ${{ secrets.FB_APP_ID }}`
`        credentials: ${{ secrets.CREDENTIAL_FILE_CONTENT }}`
`        groups: subwallet-team`
`        file: output.ipa`

- Output:
![image](https://github.com/nickwph/firebase-app-distribution-action/assets/6987808/86f618ca-9eb7-4c84-ad82-d63f2ef9cff4)

Pls, help me solving this, if you need further information, just ask me. Many thanks!

**Comment by nickwph** [comment]
It seems more like an issue with you IPA file. Maybe you could set `debug: true` to see what's the detailed error message first? Also you could try to make sure you can upload using `firebase-tools`.

**Comment by nguyenduythuc** [comment]
Thanks! Turns out i was distributed my app with android app id. Silly me :(

**Comment by nguyenduythuc** [comment]
Hi @nickwph, my app was uploaded perfectly from my last comment until yesterday. 
I think there is a issue with Firebase or your library is out of date with Firebase. I haven't change any configuration from last success build, here is the workflow code https://github.com/Koniverse/SubWallet-Mobile/actions/runs/7126526446/workflow
This is error log
![image](https://github.com/nickwph/firebase-app-distribution-action/assets/6987808/ec807f5c-3fef-46f5-b11d-d34a06a81d00)

**Comment by nickwph** [comment]
Hello @nguyenduythuc, seems like firebase tools updated that it needs NodeJS version 18 or above. I believe your project is using older version of NodeJS. I suggest you update your project to switch to this version before running the distirbution script: https://github.com/marketplace/actions/setup-node-js-environment

```
- uses: actions/setup-node@v4
  with:
    node-version: '18.x'
```

At the mean time let me see what i could do to do the same from my script.

**Comment by nguyenduythuc** [comment]
Thanks @nickwph! It worked.
